version: '3.8'

services:
  ml-service:
    build: .
    container_name: ml-service
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: "file:///app/mlruns"
    volumes:
      - ./mlruns:/app/mlruns
    restart: unless-stopped
